import { TUser } from "@/types/columnTypes";

export const supportDatas: TUser[] = [
  {
    id: "01",
    name: "Rahim Uddin",
    email: "rahim.uddin@example.com",
    number: "+8801712345678",
    location: "Dhaka",
    isService: true,
    status: "Pending",
  },
  {
    id: "02",
    name: "Karim Hossain",
    email: "karim.hossain@example.com",
    number: "+8801811122233",
    location: "Chattogram",
    status: "Solved",
  },
  {
    id: "03",
    name: "Nusrat Jahan",
    email: "nusrat.jahan@example.com",
    number: "+8801919988776",
    location: "Sylhet",
    isService: false,
    status: "Pending",
  },
  {
    id: "04",
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@example.com",
    number: "+8801612349988",
    location: "Rajshahi",
    status: "Pending",
  },
  {
    id: "05",
    name: "Farzana Islam",
    email: "farzana.islam@example.com",
    number: "+8801710098877",
    location: "Khulna",
    isService: true,
    status: "Solved",
  },
  {
    id: "06",
    name: "Sabbir Rahman",
    email: "sabbir.rahman@example.com",
    number: "+8801912345566",
    location: "Barishal",
    status: "Pending",
  },
  {
    id: "07",
    name: "Mehedi Hasan",
    email: "mehedi.hasan@example.com",
    number: "+8801815678899",
    location: "Mymensingh",
    isService: false,
    status: "Pending",
  },
  {
    id: "08",
    name: "Ayesha Akter",
    email: "ayesha.akter@example.com",
    number: "+8801619988774",
    location: "Cumilla",
    status: "Solved",
  },
  {
    id: "09",
    name: "Imran Khan",
    email: "imran.khan@example.com",
    number: "+8801715566778",
    location: "Gazipur",
    isService: true,
    status: "Pending",
  },
  {
    id: "10",
    name: "Rifat Mahmud",
    email: "rifat.mahmud@example.com",
    number: "+8801912233445",
    location: "Narayanganj",
    status: "Pending",
  },
];
